name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    # Skip if the commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set version from tag
      id: get_version
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Use our sync-version script instead of manual updates
        npm version $VERSION --no-git-tag-version --allow-same-version
        set -e
        node scripts/sync-version.js || { echo "Error: sync-version.js failed"; exit 1; }
        
        # Commit version updates with [skip ci] to avoid circular trigger
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add package.json public/manifest.json version.txt
        git commit -m "chore: Sync versions to $VERSION [skip ci]"
        git push origin HEAD:main

    - name: Build
      run: npm run build
      env:
        NODE_ENV: production

    - name: Create artifacts directory
      run: mkdir -p artifacts

    - name: Create versioned zip
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cd dist
        zip -r "../artifacts/azure-devops-wiki-editor-v${{ steps.get_version.outputs.version }}.zip" *

    - name: Upload build artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: extension-dist-v${{ steps.get_version.outputs.version }}
        path: artifacts/azure-devops-wiki-editor-v${{ steps.get_version.outputs.version }}.zip
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Get Version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: extension-dist-v${{ steps.get_version.outputs.version }}
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/azure-devops-wiki-editor-v${{ steps.get_version.outputs.version }}.zip
        generate_release_notes: true
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
